# Generated by Django 2.1.7 on 2019-05-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_year', models.DateField()),
                ('birth_year1', models.CharField(choices=[('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984')], max_length=4)),
                ('favorite_colors', models.CharField(choices=[('az', 'Azul'), ('vd', 'Verde'), ('pt', 'Preto')], max_length=2)),
            ],
        ),
    ]
