# Generated by Django 2.1.7 on 2019-05-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cnpj', models.CharField(max_length=15)),
                ('fone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=300)),
            ],
        ),
    ]
