# Generated by Django 2.1.7 on 2019-05-18 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('dataInicial', models.DateField(verbose_name='data inicial')),
                ('dataFinal', models.DateField(verbose_name='data final')),
            ],
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name_plural': 'fornecedores'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(error_messages={'required': 'Obrigatório o preenchimento do nome!'}, max_length=250),
        ),
        migrations.AddField(
            model_name='agenda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
    ]
