# Generated by Django 2.1.7 on 2019-05-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190517_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dataFinal',
            field=models.DateTimeField(verbose_name='data final'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='dataInicial',
            field=models.DateTimeField(verbose_name='data inicial'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
    ]
